[phases.setup]
aptPkgs = [
    "build-essential",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libjpeg-dev",
    "libgif-dev",
    "librsvg2-dev",
    "libpixman-1-dev",
] # Install the wget package with apt-get
